server:
  port: 9001

spring:
  application:
    name: SimpleTaskManagerSystem

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simple-task-manager-system-db
    username: doda
    password: doda
    hikari:
      schema: ${my.db.schemaName}
      idle-timeout: 120000
      max-lifetime: 300000

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${my.db.schemaName}

  liquibase:
    enabled: true
    default-schema: ${my.db.schemaName}

my:
  db:
    schemaName: taskserviceapp

token:
  signing:
    key: EDIT_THIS_KEY
